site_name: Beekeeper Studio
theme:
  logo: assets/bks.svg
  name: material
  font:
    text: Rubik
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - search.highlight
  palette:
    scheme: slate
    primary: custom
    accent: custom

extra_css:
  - stylesheets/extra.css
plugins:
  - search
