name: Studio - Unit Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - master
    paths-ignore:
      - apps/sqltools/**
  pull_request:
    paths-ignore:
      - apps/sqltools/**

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      test-chunks: ${{ steps['set-test-chunks'].outputs['test-chunks'] }}
    steps:
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2
        with:
          version: "1.7"
          force: true

      - uses: actions/checkout@v2
      - id: set-test-chunks
        name: Set Chunks
        run: echo "::set-output name=test-chunks::$(./bin/get-db-files-as-json.sh)"
  unit:
    name: Normal Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn workspace beekeeper-studio run lint

      - name: Check for bad files
        run: bin/check-for-only-tests.sh

      - name: Unit Tests
        run: yarn workspace beekeeper-studio run test:unit --ci --silent

      - name: Non-DB Integration Tests
        run: yarn workspace beekeeper-studio run test:ci --ci --silent


  integration:
    name: test - ${{ split(matrix.chunk)[-1] }}
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      matrix:
        chunk: ${{ fromJson(needs.setup.outputs['test-chunks']) }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Integration Tests
        run: yarn workspace beekeeper-studio run test:integration --runInBand --ci --silent ${{ matrix.chunk }}
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
